# Generated by Django 5.2.6 on 2025-10-06 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_client_owner_mailing_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("view_all_clients", "Может просматривать всех клиентов")
                ],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылок",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("view_all_mailings", "Может просматривать все рассылки")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("view_all_messages", "Может просматривать все сообщения")
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
    ]
